### ISSUE TITLE
Wrong url path in docs

### ISSUE THREAD

**Issue by acateon** [CyanLabs/jsonapi-unraid#1]
Docks show example path as:
http://TOWER/plugins/jsonapi/disks.php?file=disks.ini

Should be:

http://TOWER/plugins/jsonapi/api.php?file=disks.ini

?

**Comment by fma965** [comment]
Yes you are right, thanks.

**Comment by fma965** [comment]
https://github.com/Fma965/jsonapi-unraid/commit/c2cffc44d5c16f44f4889575f28fbeb01d297c32
